version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /pfam_funcAnno/wdl/pfam_anno.wdl
    testParameterFiles:
      - /optional.json
    name: pfam_anno
  - subclass: WDL
    primaryDescriptorPath: /cpc2_funcAnno/wdl/cpc2_anno.wdl
    testParameterFiles:
      - /optional.json
    name: cpc2_anno
