version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /pfam_funcAnno/wdl/pfam_anno.wdl
    testParameterFiles:
      - /optional.json
    name: pfam_anno
  - subclass: WDL
    primaryDescriptorPath: /cpc2_funcAnno/wdl/cpc2_anno.wdl
    testParameterFiles:
      - /optional.json
    name: cpc2_anno
  - subclass: WDL
    primaryDescriptorPath: /DeepTMHMM_funcAnno/wdl/DeepTMHMM_anno.wdl
    testParameterFiles:
      - /optional.json
    name: tmhmm_anno
  - subclass: WDL
    primaryDescriptorPath: /DeepTMHMM_large_input/wdl/DeepTMHMM_anno_chunked.wdl
    testParameterFiles:
      - /optional.json
    name: tmhmm_chunked
  - subclass: WDL
    primaryDescriptorPath: /tmhmm2_funcAnno/wdl/tmhmm_v2.wdl
    testParameterFiles:
      - /optional.json
    name: tmhmmv2_anno    
  - subclass: WDL
    primaryDescriptorPath: /iupred2_funcAnno/wdl/iupred2_anno.wdl
    testParameterFiles:
      - /optional.json
    name: iupred2a_anno
  - subclass: WDL
    primaryDescriptorPath: /SignalP6_funcAnno/wdl/signalp_anno.wdl
    testParameterFiles:
      - /optional.json
    name: signalp6_anno
  - subclass: WDL
    primaryDescriptorPath: /anno_main.wdl
    testParameterFiles:
      - /optional.json
    name: func_anno_main



